use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

use alveus_types::EnclosureId;

fn main() {
    let path = Path::new(&env::var("OUT_DIR").unwrap()).join("poop_configs.rs");
    let mut file = BufWriter::new(File::create(&path).unwrap());

    write!(
        &mut file,
        "// @generated by crates/alveus-configs/build.rs — do not edit.\n\
         static POOP_CONFIGS: phf::Map<EnclosureId, PoopConfig> = {};\n",
        phf_codegen::Map::new()
            .entry(
                EnclosureId::PushPopEnclosure,
                "PoopConfig {\n\
                 \x20       spawn_thresholds: &[alveus_types::Stat(800), alveus_types::Stat(500), alveus_types::Stat(200)],\n\
                 \x20       poop_decay_rate: 20.0,\n\
                 \x20       cleanliness_restore_per_poop: alveus_types::CleanStat(alveus_types::Stat(350)),\n\
                 \x20       spawn_bounds: PUSH_POP_PLACEMENT.wander_bounds,\n\
                 \x20   }",
            )
            .build()
    )
    .unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
